name: Continuous Integration and Deployment
on: [push, pull_request]
jobs: 
  build:
      name: Build and test 
      runs-on: ubuntu-latest 
      env:
        TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
      steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build --target test --tag todo-app:test .

      - name: Test
        run: docker run todo-app:test ./todo_app/tests

      - name: E2E Tests
        run: docker run -e TRELLO_API_KEY -e TRELLO_API_TOKEN todo-app:test ./todo_app/tests_e2e
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin docker.io

    - name: Build the image
      run: docker build --target production --tag avgopal/todo-app:latest .

    - name: Push the image to DockerHub
      run: docker push avgopal/todo-app
