name: Continuous Integration
on: [push, pull_request]
jobs: 
  build:
      name: Build and test 
      runs-on: ubuntu-latest 
      env:
        TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
      steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build --target test --tag todo-app:test .

      - name: Tests
        run: docker run todo-app:test ./todo_app/tests

      - name: E2E Tests
        run: docker run -e TRELLO_API_KEY -e TRELLO_API_TOKEN todo-app:test ./todo_app/tests_e2e